%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'baseline';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('baseline.log');
M_.exo_names = 'e_a';
M_.exo_names_tex = 'e\_a';
M_.exo_names_long = 'e_a';
M_.exo_names = char(M_.exo_names, 'e_nu');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_nu');
M_.exo_names_long = char(M_.exo_names_long, 'e_nu');
M_.endo_names = 'lamb';
M_.endo_names_tex = 'lamb';
M_.endo_names_long = 'lamb';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'pi_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_star');
M_.endo_names_long = char(M_.endo_names_long, 'pi_star');
M_.endo_names = char(M_.endo_names, 'x1');
M_.endo_names_tex = char(M_.endo_names_tex, 'x1');
M_.endo_names_long = char(M_.endo_names_long, 'x1');
M_.endo_names = char(M_.endo_names, 'x2');
M_.endo_names_tex = char(M_.endo_names_tex, 'x2');
M_.endo_names_long = char(M_.endo_names_long, 'x2');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'w_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_star');
M_.endo_names_long = char(M_.endo_names_long, 'w_star');
M_.endo_names = char(M_.endo_names, 'h1');
M_.endo_names_tex = char(M_.endo_names_tex, 'h1');
M_.endo_names_long = char(M_.endo_names_long, 'h1');
M_.endo_names = char(M_.endo_names, 'h2');
M_.endo_names_tex = char(M_.endo_names_tex, 'h2');
M_.endo_names_long = char(M_.endo_names_long, 'h2');
M_.endo_names = char(M_.endo_names, 'vp');
M_.endo_names_tex = char(M_.endo_names_tex, 'vp');
M_.endo_names_long = char(M_.endo_names_long, 'vp');
M_.endo_names = char(M_.endo_names, 'vw');
M_.endo_names_tex = char(M_.endo_names_tex, 'vw');
M_.endo_names_long = char(M_.endo_names_long, 'vw');
M_.endo_names = char(M_.endo_names, 'aleph');
M_.endo_names_tex = char(M_.endo_names_tex, 'aleph');
M_.endo_names_long = char(M_.endo_names_long, 'aleph');
M_.endo_names = char(M_.endo_names, 'nu');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu');
M_.endo_names_long = char(M_.endo_names_long, 'nu');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'utility');
M_.endo_names_tex = char(M_.endo_names_tex, 'utility');
M_.endo_names_long = char(M_.endo_names_long, 'utility');
M_.endo_names = char(M_.endo_names, 'MULT_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_1');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_1');
M_.endo_names = char(M_.endo_names, 'MULT_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_2');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_2');
M_.endo_names = char(M_.endo_names, 'MULT_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_3');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_3');
M_.endo_names = char(M_.endo_names, 'MULT_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_4');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_4');
M_.endo_names = char(M_.endo_names, 'MULT_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_5');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_5');
M_.endo_names = char(M_.endo_names, 'MULT_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_6');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_6');
M_.endo_names = char(M_.endo_names, 'MULT_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_7');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_7');
M_.endo_names = char(M_.endo_names, 'MULT_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_8');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_8');
M_.endo_names = char(M_.endo_names, 'MULT_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_9');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_9');
M_.endo_names = char(M_.endo_names, 'MULT_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_10');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_10');
M_.endo_names = char(M_.endo_names, 'MULT_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_11');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_11');
M_.endo_names = char(M_.endo_names, 'MULT_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_12');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_12');
M_.endo_names = char(M_.endo_names, 'MULT_13');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_13');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_13');
M_.endo_names = char(M_.endo_names, 'MULT_14');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_14');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_14');
M_.endo_names = char(M_.endo_names, 'MULT_15');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_15');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_15');
M_.endo_names = char(M_.endo_names, 'MULT_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_16');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_16');
M_.endo_names = char(M_.endo_names, 'MULT_17');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_17');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_17');
M_.endo_names = char(M_.endo_names, 'MULT_18');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_18');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_18');
M_.endo_names = char(M_.endo_names, 'MULT_19');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_19');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_19');
M_.endo_names = char(M_.endo_names, 'MULT_20');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_20');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_20');
M_.endo_names = char(M_.endo_names, 'MULT_21');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_21');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_21');
M_.endo_partitions = struct();
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'alphap');
M_.param_names_tex = char(M_.param_names_tex, 'alphap');
M_.param_names_long = char(M_.param_names_long, 'alphap');
M_.param_names = char(M_.param_names, 'alphaw');
M_.param_names_tex = char(M_.param_names_tex, 'alphaw');
M_.param_names_long = char(M_.param_names_long, 'alphaw');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'kappaw');
M_.param_names_tex = char(M_.param_names_tex, 'kappaw');
M_.param_names_long = char(M_.param_names_long, 'kappaw');
M_.param_names = char(M_.param_names, 'kappap');
M_.param_names_tex = char(M_.param_names_tex, 'kappap');
M_.param_names_long = char(M_.param_names_long, 'kappap');
M_.param_names = char(M_.param_names, 'rhoi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoi');
M_.param_names_long = char(M_.param_names_long, 'rhoi');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names_long = char(M_.param_names_long, 'rhoa');
M_.param_names = char(M_.param_names, 'rhonu');
M_.param_names_tex = char(M_.param_names_tex, 'rhonu');
M_.param_names_long = char(M_.param_names_long, 'rhonu');
M_.param_names = char(M_.param_names, 'phii');
M_.param_names_tex = char(M_.param_names_tex, 'phii');
M_.param_names_long = char(M_.param_names_long, 'phii');
M_.param_names = char(M_.param_names, 'phipi');
M_.param_names_tex = char(M_.param_names_tex, 'phipi');
M_.param_names_long = char(M_.param_names_long, 'phipi');
M_.param_names = char(M_.param_names, 'phiy');
M_.param_names_tex = char(M_.param_names_tex, 'phiy');
M_.param_names_long = char(M_.param_names_long, 'phiy');
M_.param_names = char(M_.param_names, 'pi_target');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_target');
M_.param_names_long = char(M_.param_names_long, 'pi_target');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'lambs');
M_.param_names_tex = char(M_.param_names_tex, 'lambs');
M_.param_names_long = char(M_.param_names_long, 'lambs');
M_.param_names = char(M_.param_names, 'cs');
M_.param_names_tex = char(M_.param_names_tex, 'cs');
M_.param_names_long = char(M_.param_names_long, 'cs');
M_.param_names = char(M_.param_names, 'ys');
M_.param_names_tex = char(M_.param_names_tex, 'ys');
M_.param_names_long = char(M_.param_names_long, 'ys');
M_.param_names = char(M_.param_names, 'ns');
M_.param_names_tex = char(M_.param_names_tex, 'ns');
M_.param_names_long = char(M_.param_names_long, 'ns');
M_.param_names = char(M_.param_names, 'is');
M_.param_names_tex = char(M_.param_names_tex, 'is');
M_.param_names_long = char(M_.param_names_long, 'is');
M_.param_names = char(M_.param_names, 'rs');
M_.param_names_tex = char(M_.param_names_tex, 'rs');
M_.param_names_long = char(M_.param_names_long, 'rs');
M_.param_names = char(M_.param_names, 'ms');
M_.param_names_tex = char(M_.param_names_tex, 'ms');
M_.param_names_long = char(M_.param_names_long, 'ms');
M_.param_names = char(M_.param_names, 'pis');
M_.param_names_tex = char(M_.param_names_tex, 'pis');
M_.param_names_long = char(M_.param_names_long, 'pis');
M_.param_names = char(M_.param_names, 'pi_stars');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_stars');
M_.param_names_long = char(M_.param_names_long, 'pi_stars');
M_.param_names = char(M_.param_names, 'x1s');
M_.param_names_tex = char(M_.param_names_tex, 'x1s');
M_.param_names_long = char(M_.param_names_long, 'x1s');
M_.param_names = char(M_.param_names, 'x2s');
M_.param_names_tex = char(M_.param_names_tex, 'x2s');
M_.param_names_long = char(M_.param_names_long, 'x2s');
M_.param_names = char(M_.param_names, 'mcs');
M_.param_names_tex = char(M_.param_names_tex, 'mcs');
M_.param_names_long = char(M_.param_names_long, 'mcs');
M_.param_names = char(M_.param_names, 'ws');
M_.param_names_tex = char(M_.param_names_tex, 'ws');
M_.param_names_long = char(M_.param_names_long, 'ws');
M_.param_names = char(M_.param_names, 'w_stars');
M_.param_names_tex = char(M_.param_names_tex, 'w\_stars');
M_.param_names_long = char(M_.param_names_long, 'w_stars');
M_.param_names = char(M_.param_names, 'h1s');
M_.param_names_tex = char(M_.param_names_tex, 'h1s');
M_.param_names_long = char(M_.param_names_long, 'h1s');
M_.param_names = char(M_.param_names, 'h2s');
M_.param_names_tex = char(M_.param_names_tex, 'h2s');
M_.param_names_long = char(M_.param_names_long, 'h2s');
M_.param_names = char(M_.param_names, 'vps');
M_.param_names_tex = char(M_.param_names_tex, 'vps');
M_.param_names_long = char(M_.param_names_long, 'vps');
M_.param_names = char(M_.param_names, 'vws');
M_.param_names_tex = char(M_.param_names_tex, 'vws');
M_.param_names_long = char(M_.param_names_long, 'vws');
M_.param_names = char(M_.param_names, 'alephs');
M_.param_names_tex = char(M_.param_names_tex, 'alephs');
M_.param_names_long = char(M_.param_names_long, 'alephs');
M_.param_names = char(M_.param_names, 'nus');
M_.param_names_tex = char(M_.param_names_tex, 'nus');
M_.param_names_long = char(M_.param_names_long, 'nus');
M_.param_names = char(M_.param_names, 'as');
M_.param_names_tex = char(M_.param_names_tex, 'as');
M_.param_names_long = char(M_.param_names_long, 'as');
M_.param_names = char(M_.param_names, 'utilitys');
M_.param_names_tex = char(M_.param_names_tex, 'utilitys');
M_.param_names_long = char(M_.param_names_long, 'utilitys');
M_.param_names = char(M_.param_names, 'optimal_policy_discount_factor');
M_.param_names_tex = char(M_.param_names_tex, 'optimal\_policy\_discount\_factor');
M_.param_names_long = char(M_.param_names_long, 'optimal_policy_discount_factor');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 43;
M_.param_nbr = 43;
M_.orig_endo_nbr = 22;
M_.aux_vars(1).endo_index = 23;
M_.aux_vars(1).type = 6;
M_.aux_vars(1).eq_nbr = 1;
M_.aux_vars(2).endo_index = 24;
M_.aux_vars(2).type = 6;
M_.aux_vars(2).eq_nbr = 2;
M_.aux_vars(3).endo_index = 25;
M_.aux_vars(3).type = 6;
M_.aux_vars(3).eq_nbr = 3;
M_.aux_vars(4).endo_index = 26;
M_.aux_vars(4).type = 6;
M_.aux_vars(4).eq_nbr = 4;
M_.aux_vars(5).endo_index = 27;
M_.aux_vars(5).type = 6;
M_.aux_vars(5).eq_nbr = 5;
M_.aux_vars(6).endo_index = 28;
M_.aux_vars(6).type = 6;
M_.aux_vars(6).eq_nbr = 6;
M_.aux_vars(7).endo_index = 29;
M_.aux_vars(7).type = 6;
M_.aux_vars(7).eq_nbr = 7;
M_.aux_vars(8).endo_index = 30;
M_.aux_vars(8).type = 6;
M_.aux_vars(8).eq_nbr = 8;
M_.aux_vars(9).endo_index = 31;
M_.aux_vars(9).type = 6;
M_.aux_vars(9).eq_nbr = 9;
M_.aux_vars(10).endo_index = 32;
M_.aux_vars(10).type = 6;
M_.aux_vars(10).eq_nbr = 10;
M_.aux_vars(11).endo_index = 33;
M_.aux_vars(11).type = 6;
M_.aux_vars(11).eq_nbr = 11;
M_.aux_vars(12).endo_index = 34;
M_.aux_vars(12).type = 6;
M_.aux_vars(12).eq_nbr = 12;
M_.aux_vars(13).endo_index = 35;
M_.aux_vars(13).type = 6;
M_.aux_vars(13).eq_nbr = 13;
M_.aux_vars(14).endo_index = 36;
M_.aux_vars(14).type = 6;
M_.aux_vars(14).eq_nbr = 14;
M_.aux_vars(15).endo_index = 37;
M_.aux_vars(15).type = 6;
M_.aux_vars(15).eq_nbr = 15;
M_.aux_vars(16).endo_index = 38;
M_.aux_vars(16).type = 6;
M_.aux_vars(16).eq_nbr = 16;
M_.aux_vars(17).endo_index = 39;
M_.aux_vars(17).type = 6;
M_.aux_vars(17).eq_nbr = 17;
M_.aux_vars(18).endo_index = 40;
M_.aux_vars(18).type = 6;
M_.aux_vars(18).eq_nbr = 18;
M_.aux_vars(19).endo_index = 41;
M_.aux_vars(19).type = 6;
M_.aux_vars(19).eq_nbr = 19;
M_.aux_vars(20).endo_index = 42;
M_.aux_vars(20).type = 6;
M_.aux_vars(20).eq_nbr = 20;
M_.aux_vars(21).endo_index = 43;
M_.aux_vars(21).type = 6;
M_.aux_vars(21).eq_nbr = 21;
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('baseline_static');
erase_compiled_function('baseline_dynamic');
M_.orig_eq_nbr = 21;
M_.eq_nbr = 43;
M_.ramsey_eq_nbr = 22;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 18 61;
 1 19 62;
 0 20 0;
 0 21 0;
 2 22 0;
 0 23 0;
 0 24 0;
 3 25 63;
 0 26 0;
 0 27 64;
 0 28 65;
 0 29 0;
 4 30 66;
 5 31 67;
 0 32 68;
 0 33 69;
 6 34 0;
 7 35 0;
 8 36 0;
 9 37 70;
 10 38 0;
 0 39 0;
 11 40 71;
 12 41 0;
 0 42 0;
 13 43 0;
 14 44 0;
 0 45 72;
 0 46 0;
 0 47 73;
 0 48 74;
 0 49 75;
 0 50 76;
 0 51 0;
 15 52 0;
 16 53 0;
 0 54 0;
 0 55 0;
 0 56 77;
 0 57 78;
 0 58 0;
 17 59 0;
 0 60 79;]';
M_.nstatic = 13;
M_.nfwrd   = 13;
M_.npred   = 11;
M_.nboth   = 6;
M_.nsfwrd   = 19;
M_.nspred   = 17;
M_.ndynamic   = 30;
M_.equations_tags = {
  1 , 'name' , '(2)home Euler equation' ;
  2 , 'name' , '(3)home Euler equation' ;
  3 , 'name' , '(4)optimal wage decision' ;
  4 , 'name' , '(5)auxiliary h1' ;
  5 , 'name' , '(6)auxiliary h2' ;
  6 , 'name' , '(7)wage index' ;
  7 , 'name' , '(8)production technology' ;
  8 , 'name' , '(9)the price dispersion' ;
  9 , 'name' , '(10)the wage dispersion' ;
  10 , 'name' , '(11)the wage dispersion' ;
  11 , 'name' , '(12)inflatin evolution' ;
  12 , 'name' , '(13)optimal price decision' ;
  13 , 'name' , '(14)auxiliary variable x1' ;
  14 , 'name' , '(15) auxiliary variable x2' ;
  15 , 'name' , '(16)wage decision' ;
  16 , 'name' , '(17)resource constraint' ;
  17 , 'name' , '(18)technology shock' ;
  18 , 'name' , '(19)perference shock' ;
  19 , 'name' , '(20)money balance demand' ;
  20 , 'name' , '(21)Fisher equation' ;
  21 , 'name' , '(22)utility function' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(43, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(43, 1);
M_.NNZDerivatives = [326; 1196; -1];
M_.params( 1 ) = 0.9937;
beta = M_.params( 1 );
M_.params( 4 ) = 0.40;
alpha = M_.params( 4 );
M_.params( 2 ) = 0.6410;
b = M_.params( 2 );
M_.params( 3 ) = 1.8862;
eta = M_.params( 3 );
M_.params( 5 ) = 3.13;
gamma = M_.params( 5 );
M_.params( 6 ) = 9.30;
theta = M_.params( 6 );
M_.params( 7 ) = 6.00;
epsilon = M_.params( 7 );
M_.params( 8 ) = 0.6114;
alphap = M_.params( 8 );
M_.params( 9 ) = 0.5860;
alphaw = M_.params( 9 );
M_.params( 11 ) = 0.5213;
kappaw = M_.params( 11 );
M_.params( 12 ) = 0.5705;
kappap = M_.params( 12 );
M_.params( 16 ) = 0.8624;
phii = M_.params( 16 );
M_.params( 17 ) = 1.2792;
phipi = M_.params( 17 );
M_.params( 18 ) = 0.2860;
phiy = M_.params( 18 );
M_.params( 13 ) = 0.6721;
rhoi = M_.params( 13 );
M_.params( 14 ) = 0.6536;
rhoa = M_.params( 14 );
M_.params( 15 ) = 0.3894;
rhonu = M_.params( 15 );
M_.params( 10 ) = 7.182975795587264;
chi = M_.params( 10 );
M_.params( 20 ) = 0.5;
omega = M_.params( 20 );
M_.params( 19 ) = 0.00;
pi_target = M_.params( 19 );
M_.params( 41 ) = 1;
as = M_.params( 41 );
M_.params( 40 ) = 1;
nus = M_.params( 40 );
M_.params( 24 ) = 0.3833333333333333;
ns = M_.params( 24 );
M_.params( 28 ) = (1+M_.params(19)/100)^0.25;
pis = M_.params( 28 );
M_.params( 25 ) = M_.params(28)/M_.params(1);
is = M_.params( 25 );
M_.params( 26 ) = M_.params(25)/M_.params(28);
rs = M_.params( 26 );
M_.params( 29 ) = ((M_.params(28)^(1-M_.params(7))-M_.params(8)*M_.params(28)^((1-M_.params(7))*M_.params(12)))/(1-M_.params(8)))^(1/(1-M_.params(7)));
pi_stars = M_.params( 29 );
M_.params( 37 ) = (1-M_.params(8))*(M_.params(28)/M_.params(29))^(M_.params(7)/(1-M_.params(4)))/(1-M_.params(8)*M_.params(28)^(M_.params(7)/(1-M_.params(4))*(1-M_.params(12))));
vps = M_.params( 37 );
M_.params( 32 ) = (M_.params(7)-1)/M_.params(7)*(M_.params(29)/M_.params(28))^(1+M_.params(7)*M_.params(4)/(1-M_.params(4)))*(1-M_.params(28)^(M_.params(7)/(1-M_.params(4))*(1-M_.params(12)))*M_.params(1)*M_.params(8))/(1-M_.params(1)*M_.params(8)*M_.params(28)^((1-M_.params(12))*(M_.params(7)-1)));
mcs = M_.params( 32 );
M_.params( 33 ) = M_.params(37)*(1-M_.params(4))*M_.params(32)*(M_.params(24)/M_.params(37))^(1-M_.params(4))/M_.params(24);
ws = M_.params( 33 );
M_.params( 34 ) = M_.params(33)*((1-M_.params(9)*M_.params(28)^((1-M_.params(11))*(M_.params(6)-1)))/(1-M_.params(9)))^(1/(1-M_.params(6)));
w_stars = M_.params( 34 );
M_.params( 38 ) = (1-M_.params(9))*(M_.params(34)/M_.params(33))^(-M_.params(6))/(1-M_.params(9)*M_.params(28)^((1-M_.params(11))*M_.params(6)));
vws = M_.params( 38 );
M_.params( 39 ) = (1-M_.params(9))*(M_.params(34)/M_.params(33))^((-M_.params(6))*(1+M_.params(3)))/(1-M_.params(9)*M_.params(28)^((1-M_.params(11))*M_.params(6)*(1+M_.params(3))));
alephs = M_.params( 39 );
M_.params( 10 ) = M_.params(34)*(M_.params(6)-1)/M_.params(6)/M_.params(24)^(1-M_.params(4)+M_.params(3))*(M_.params(34)/M_.params(33))^(M_.params(6)*M_.params(3))*(1-M_.params(1)*M_.params(2))/(1-M_.params(2))*M_.params(37)^(1-M_.params(4))*(1-M_.params(28)^((1-M_.params(11))*M_.params(6)*(1+M_.params(3)))*M_.params(1)*M_.params(9))/(1-M_.params(28)^((1-M_.params(11))*(M_.params(6)-1))*M_.params(1)*M_.params(9));
chi = M_.params( 10 );
M_.params( 23 ) = (M_.params(24)/M_.params(37))^(1-M_.params(4))*M_.params(41);
ys = M_.params( 23 );
M_.params( 22 ) = M_.params(23);
cs = M_.params( 22 );
M_.params( 21 ) = (1-M_.params(1)*M_.params(2))*M_.params(40)/(M_.params(22)-M_.params(2)*M_.params(22));
lambs = M_.params( 21 );
M_.params( 27 ) = (M_.params(21)*(1-1/M_.params(25)))^((-1)/M_.params(5));
ms = M_.params( 27 );
M_.params( 30 ) = M_.params(23)*M_.params(32)*M_.params(21)/(1-M_.params(1)*M_.params(8)*M_.params(28)^(M_.params(7)*(1-M_.params(12))/(1-M_.params(4))));
x1s = M_.params( 30 );
M_.params( 31 ) = M_.params(23)*M_.params(21)/(1-M_.params(1)*M_.params(8)*M_.params(28)^((1-M_.params(12))*(M_.params(7)-1)));
x2s = M_.params( 31 );
M_.params( 35 ) = M_.params(10)*M_.params(24)^(1+M_.params(3))*(M_.params(33)/M_.params(34))^(M_.params(6)*(1+M_.params(3)))/(1-M_.params(28)^((1-M_.params(11))*M_.params(6)*(1+M_.params(3)))*M_.params(1)*M_.params(9));
h1s = M_.params( 35 );
M_.params( 36 ) = M_.params(24)*M_.params(21)*(M_.params(33)/M_.params(34))^M_.params(6)/(1-M_.params(28)^((1-M_.params(11))*(M_.params(6)-1))*M_.params(1)*M_.params(9));
h2s = M_.params( 36 );
M_.params( 42 ) = log(M_.params(22)-M_.params(2)*M_.params(22))-M_.params(10)*M_.params(24)^(1+M_.params(3))*M_.params(39)/(1+M_.params(3));
utilitys = M_.params( 42 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(2, 2) = (0.0296)^2;
M_.params( 43 ) = M_.params(1);
optimal_policy_discount_factor = M_.params( 43 );
options_.ramsey_policy = 1;
options_.instruments = char('i');
options_.irf = 40;
options_.nograph = 1;
options_.order = 2;
var_list_ = char();
info = stoch_simul(var_list_);
evaluate_planner_objective;
save('baseline_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('baseline_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('baseline_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('baseline_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('baseline_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('baseline_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('baseline_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
