function [ys_, params, info] = baseline_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(20)=params(40);
    ys_(21)=params(41);
    ys_(8)=params(28);
    ys_(5)=params(25);
    ys_(6)=params(26);
    ys_(9)=params(29);
    ys_(17)=params(37);
    ys_(12)=params(32);
    ys_(13)=params(33);
    ys_(14)=params(34);
    ys_(18)=params(38);
    ys_(19)=params(39);
    ys_(4)=params(24);
    ys_(3)=params(23);
    ys_(2)=params(22);
    ys_(1)=params(21);
    ys_(7)=params(27);
    ys_(10)=params(30);
    ys_(11)=params(31);
    ys_(15)=params(35);
    ys_(16)=params(36);
    ys_(22)=params(42);
    % Auxiliary equations
    check_=0;
end
